language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
cache: cargo
branches:
  only:
    - master
    - support/1.x
    - support/2.x
before_script:
  - cargo install --force cargo-audit
script:
  - cargo test
  - cargo test --example google
  - cargo test --example github
  - cargo test --example msgraph
  - cargo test --no-default-features --features "futures-03"
  - cargo audit
notifications:
  email:
    on_success: never
