[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "3.0.0-alpha.5"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"
edition = "2018"

[features]
default = ["reqwest"]

[dependencies]
base64 = "0.9"
curl = { version = "0.4.0", optional = true }
failure = "0.1"
failure_derive = "0.1"
futures-preview = "=0.3.0-alpha.19"
http = "0.1"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.7"
tokio-io = "0.2.0-alpha.6"
url = "2.1"

[dependencies.reqwest]
version = "0.10.0-alpha.1"
optional = true
features = ["blocking"]

[dev-dependencies]
tokio = "0.2.0-alpha.6"
